alter table Movie drop constraint FK58ei722nkftq8et0d1047q4ro
alter table Movie drop constraint FK8n8hmglai6hjs0rkdt86t4pqc
drop table if exists Category cascade
drop table if exists Director cascade
drop table if exists Movie cascade
alter table Movie drop constraint FK58ei722nkftq8et0d1047q4ro
alter table Movie drop constraint FK8n8hmglai6hjs0rkdt86t4pqc
drop table if exists Category cascade
drop table if exists Director cascade
drop table if exists Movie cascade
alter table Movie drop constraint FK58ei722nkftq8et0d1047q4ro
alter table Movie drop constraint FK8n8hmglai6hjs0rkdt86t4pqc
drop table if exists Category cascade
drop table if exists Director cascade
drop table if exists Movie cascade
alter table Movie drop constraint FK58ei722nkftq8et0d1047q4ro
alter table Movie drop constraint FK8n8hmglai6hjs0rkdt86t4pqc
drop table if exists Category cascade
drop table if exists Director cascade
drop table if exists Movie cascade
alter table Movie drop constraint FK58ei722nkftq8et0d1047q4ro
alter table Movie drop constraint FK8n8hmglai6hjs0rkdt86t4pqc
drop table if exists Category cascade
drop table if exists Director cascade
drop table if exists Movie cascade
alter table Movie drop constraint FK58ei722nkftq8et0d1047q4ro
alter table Movie drop constraint FK8n8hmglai6hjs0rkdt86t4pqc
drop table if exists Category cascade
drop table if exists Director cascade
drop table if exists Movie cascade
alter table Movie drop constraint FK58ei722nkftq8et0d1047q4ro
alter table Movie drop constraint FK8n8hmglai6hjs0rkdt86t4pqc
drop table if exists Category cascade
drop table if exists Director cascade
drop table if exists Movie cascade
alter table Movie drop constraint FK58ei722nkftq8et0d1047q4ro
alter table Movie drop constraint FK8n8hmglai6hjs0rkdt86t4pqc
drop table if exists Category cascade
drop table if exists Director cascade
drop table if exists Movie cascade
alter table Movie drop constraint FK58ei722nkftq8et0d1047q4ro
alter table Movie drop constraint FK8n8hmglai6hjs0rkdt86t4pqc
drop table if exists Category cascade
drop table if exists Director cascade
drop table if exists Movie cascade
alter table Movie drop constraint FK58ei722nkftq8et0d1047q4ro
alter table Movie drop constraint FK8n8hmglai6hjs0rkdt86t4pqc
drop table if exists Category cascade
drop table if exists Director cascade
drop table if exists Movie cascade
alter table Movie drop constraint FK58ei722nkftq8et0d1047q4ro
alter table Movie drop constraint FK8n8hmglai6hjs0rkdt86t4pqc
drop table if exists Category cascade
drop table if exists Director cascade
drop table if exists Movie cascade
alter table Movie drop constraint FK58ei722nkftq8et0d1047q4ro
alter table Movie drop constraint FK8n8hmglai6hjs0rkdt86t4pqc
drop table if exists Category cascade
drop table if exists Director cascade
drop table if exists Movie cascade
alter table Movie drop constraint FK58ei722nkftq8et0d1047q4ro
alter table Movie drop constraint FK8n8hmglai6hjs0rkdt86t4pqc
drop table if exists Category cascade
drop table if exists Director cascade
drop table if exists Movie cascade
alter table Movie drop constraint FK58ei722nkftq8et0d1047q4ro
alter table Movie drop constraint FK8n8hmglai6hjs0rkdt86t4pqc
drop table if exists Category cascade
drop table if exists Director cascade
drop table if exists Movie cascade
alter table Movie drop constraint FK58ei722nkftq8et0d1047q4ro
alter table Movie drop constraint FK8n8hmglai6hjs0rkdt86t4pqc
drop table if exists Category cascade
drop table if exists Director cascade
drop table if exists Movie cascade
